name: CD-Infra

on:
  repository_dispatch: 
    types:
      - deploy

# Mencegah 2 deployment production berjalan bersamaan
concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Application
    runs-on: self-hosted
    environment: Production

    steps:
      - name: Checkout Infra
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull Image
        run: |
          docker compose pull
      
      - name: Deploy-Fontend
        run: |
          docker compose up -d app-frontend
      
      - name: Deploy-Backend
        env:
          PORT : ${{ vars.PORT }}
        run: |
          docker compose up -d app-backend-1 app-backend-2 app-backend-3
      
      - name: Docker Check
        run: |
          docker compose ps      

