name: CD-Infra

on:
  workflow_run:
    workflows:
      - CI-Infra
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Nginx
        run: |
          docker compose \
            up -d \
            --pull always \
            nginx-proxy

      - name: Check Nginx
        run: |
          docker compose ps nginx-proxy