name: CI

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Runner
        run: |
          echo "Hello from self-hosted runner"
          whoami
          docker --version
          git --version